import { Dimensions, Platform, StyleSheet } from "react-native";

const screenWidth = Dimensions.get("window").width;
const screenHeight = Dimensions.get("window").height;

const lightStyles = StyleSheet.create({
  container: {
    flex: 1,
    minWidth: screenWidth,
    minHeight: screenHeight,
    backgroundColor: "#eaeaea",
  },
  keyboardAvoidingContainer: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  authContainer: {
    width: 350,
    maxHeight: "auto",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 0.5,
    borderRadius: 20,
    borderColor: "#999",
    backgroundColor: "#dbdbdb",
    padding: 25,
  },
  authAppTitle: {
    marginTop: 7,
    fontFamily: "ReadexPro-Bold",
    fontSize: 40,
    color: "#000",
  },
  authAppTitleGradient: {
    colors: ["#3287b5", "#34bc39"],
  },
  authInput: {
    width: "100%",
    height: 50,
    marginBottom: 15,
    borderWidth: 0.5,
    borderRadius: 10,
    borderColor: "#999",
    color: "#000",
    backgroundColor: "#CCC",
    paddingHorizontal: 10,
  },
  authInputPlaceholder: {
    color: "#555",
  },
  authConfirmButton: {
    width: "100%",
    height: 50,
    marginTop: 30,
    marginBottom: 20,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 0.5,
    borderRadius: 10,
    borderColor: "#999",
    backgroundColor: "#34A853",
    paddingHorizontal: 10,
  },
  authConfirmButtonLoading: {
    backgroundColor: "#777",
  },
  authTipText: {
    fontFamily: "ReadexPro-Regular",
    color: "#111",
    fontSize: 12,
    textDecorationLine: "underline",
  },
  fullscreenArea: {
    position: "absolute",
    minWidth: screenWidth,
    minHeight: screenHeight,
    flexDirection: "row",
    zIndex: 3,
  },
  menuContainer: {
    position: "absolute",
    width: 280,
    height: screenHeight,
    left: 0,
    top: 0,
    backgroundColor: "#eaeaea",
    padding: 30,
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    zIndex: 2,
  },
  menuOptions: {
    width: "100%",
    height: "90%",
    flexDirection: "column",
    justifyContent: "center",
  },
  menuOption: {
    width: "100%",
    height: 50,
    marginVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 10,
    borderColor: "#777",
    paddingHorizontal: 10,
  },
  filteringBar: {
    minWidth: "100%",
    width: "100%",
    height: 50,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    alignSelf: "center",
    paddingHorizontal: 15,
  },
  categorySelectionButton: {
    height: 40,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 15,
    backgroundColor: "#dbdbdb",
    paddingHorizontal: 10,
  },
  selectedCategoryOption: {
    height: 40,
    borderLeftWidth: 2,
    borderColor: "#eaeaea",
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 10,
  },
  topBar: {
    minWidth: "100%",
    width: "100%",
    height: 65,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 15,
  },
  searchbar: {
    width: "100%",
    height: 45,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#dbdbdb",
    borderRadius: 20,
    paddingHorizontal: 10,
  },
  taskContainer: {
    width: "100%",
    height: screenHeight - 143,
    marginTop: 10,
    alignSelf: "center",
    flexDirection: "column",
    justifyContent: "space-between",
    borderRadius: 20,
    backgroundColor: "#dbdbdb",
    padding: 15,
  },
  emptyTrashButton: {
    width: "100%",
    height: 55,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    backgroundColor: "#EA4335",
  },
  text: {
    fontFamily: "ReadexPro-Regular",
    color: "#000",
  },
  header: {
    fontFamily: "ReadexPro-Bold",
    color: "#000",
  },
  activityIndicator: {
    color: "#000",
  },
  category: {
    height: 30,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 10,
    backgroundColor: "#d6d6d6",
    paddingHorizontal: 7,
  },
  categoryText: {
    fontFamily: "ReadexPro-Regular",
    fontSize: 12,
    color: "#000",
  },
  taskControl: {
    marginVertical: 10,
    width: "100%",
    height: 140,
    borderWidth: 1,
    borderColor: "#CCC",
    borderRadius: 15,
    overflow: "hidden",
  },
  taskLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  pendingTaskLabel: {
    marginRight: 5,
    borderWidth: 2,
    borderRadius: 5,
    borderColor: "#16739e",
    paddingHorizontal: 2,
  },
  completedTaskLabel: {
    marginRight: 5,
    borderWidth: 2,
    borderRadius: 5,
    borderColor: "#17910a",
    paddingHorizontal: 2,
  },
  urgentTaskLabel: {
    marginRight: 5,
    borderWidth: 2,
    borderRadius: 5,
    borderColor: "#720b00",
    paddingHorizontal: 2,
  },
  overdueTaskLabel: {
    borderWidth: 2,
    borderRadius: 5,
    borderColor: "#8B6913",
    paddingHorizontal: 2,
  },
  pendingTaskLabelText: {
    fontFamily: "ReadexPro-SemiBold",
    fontSize: 9,
    color: "#16739e",
  },
  completedTaskLabelText: {
    fontFamily: "ReadexPro-SemiBold",
    fontSize: 9,
    color: "#17910a",
  },
  urgentTaskLabelText: {
    fontFamily: "ReadexPro-SemiBold",
    fontSize: 9,
    color: "#720b00",
  },
  overdueTaskLabelText: {
    fontFamily: "ReadexPro-SemiBold",
    fontSize: 9,
    color: "#8B6913",
  },
  dueDateTaskLabelText: {
    fontFamily: "ReadexPro-SemiBold",
    fontSize: 12,
    color: "#000",
    paddingLeft: 3,
  },
  task: {
    height: "100%",
    justifyContent: "center",
    backgroundColor: "#ededed",
    padding: 10,
  },
  deleteTaskButton: {
    width: 70,
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    margin: 0,
    backgroundColor: "#EA4335",
  },
  markTaskAsCompletedButton: {
    width: 70,
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    margin: 0,
    backgroundColor: "#34A853",
  },
  markTaskAsPendingButton: {
    width: 70,
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    margin: 0,
    backgroundColor: "#59b2db",
  },
  webDeleteTaskButton: {
    width: 100,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    backgroundColor: "#EA4335",
  },
  webMarkTaskAsCompletedButton: {
    width: 100,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    backgroundColor: "#34A853",
  },
  webMarkTaskAsPendingButton: {
    width: 100,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    backgroundColor: "#59b2db",
  },
  taskAnalysisButton: {
    width: 55,
    height: 55,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 30,
    overflow: "hidden",
  },
  taskAnalysisFloatingMenu: {
    position: "absolute",
    top: -145,
    left: -75,
  },
  taskAnalysisFloatingMenuBox: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#c1c1c1",
    backgroundColor: "#e2e2e2",
    overflow: "hidden",
  },
  taskAnalysisFloatingMenuBottomTriangle: {
    width: 0,
    height: 0,
    backgroundColor: "transparent",
    borderStyle: "solid",
    borderTopWidth: 10,
    borderRightWidth: 10,
    borderBottomWidth: 0,
    borderLeftWidth: 10,
    borderTopColor: "#c1c1c1",
    borderRightColor: "transparent",
    borderBottomColor: "transparent",
    borderLeftColor: "transparent",
    alignSelf: "center",
  },
  taskAnalysisMenuOption: {
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderColor: "#BBB",
  },
  webTaskAnalysisButton: {
    height: 55,
    marginLeft: 17,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 30,
    backgroundColor: "#CCC",
    paddingHorizontal: 20,
  },
  addTaskButton: {
    width: 155,
    height: 55,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 30,
    backgroundColor: "#49eddc",
    paddingLeft: 10,
    overflow: "hidden",
  },
  taskPopup: {
    width: 370,
    alignItems: "center",
    borderWidth: 0.5,
    borderColor: "#777",
    borderRadius: 25,
    backgroundColor: "#e0e0e0",
    padding: 25,
  },
  taskInput: {
    width: "100%",
    height: Platform.OS === "web" ? 200 : 250,
    marginTop: 20,
    backgroundColor: "#f2f2f2",
    borderRadius: 15,
    padding: 10,
    color: "#000",
  },
  chatLeftArrow: {
    position: "absolute",
    top: 0,
    left: -10,
  },
  chatRightArrow: {
    position: "absolute",
    top: 0,
    right: -10,
  },
  chatMessageContainer: {
    maxWidth: 240,
    marginLeft: 10,
    marginBottom: 10,
    alignSelf: "flex-start",
    borderRadius: 10,
    backgroundColor: "#DDD",
    padding: 10,
  },
  chatUserMessage: {
    marginRight: 10,
    backgroundColor: "#aac9ff",
    alignSelf: "flex-end",
  },
  chatErrorMessage: {
    backgroundColor: "#d83636",
  },
  chatInputContainer: {
    width: "100%",
    height: 45,
    marginTop: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderRadius: 10,
    backgroundColor: "#f2f2f2",
  },
  chatInputSendButton: {
    width: 45,
    height: 45,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    backgroundColor: "#38ade0",
  },
  taskInsight: {
    width: "100%",
    marginTop: 10,
  },
  popupButtonRow: {
    width: "100%",
    marginTop: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  commonButton: {
    width: 100,
    height: 45,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    borderWidth: 0.5,
    borderRadius: 15,
    borderColor: "#777",
    backgroundColor: "#bfbfbf",
    paddingHorizontal: 10,
  },
  cancelButton: {
    backgroundColor: "#d83636",
  },
  confirmButton: {
    backgroundColor: "#38ade0",
  },
  confirmBigButton: {
    width: "100%",
    height: 45,
    marginTop: 20,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "flex-end",
    borderWidth: 1,
    borderRadius: 10,
    borderColor: "#d6d6d6",
    backgroundColor: "#38ade0",
    paddingHorizontal: 10,
  },
  messagePopup: {
    width: 370,
    height: 200,
    justifyContent: "space-between",
    alignItems: "flex-start",
    borderWidth: 0.5,
    borderColor: "#777",
    borderRadius: 25,
    backgroundColor: "#e0e0e0",
    padding: 25,
  },
  taskSuggestionPopup: {
    position: "absolute",
    top: 150,
    right: 40,
    width: 200,
    flexDirection: "column",
    alignItems: "center",
    borderWidth: 0.5,
    borderColor: "#777",
    borderRadius: 20,
    backgroundColor: "#d6d6d6",
    overflow: "hidden",
    zIndex: 3,
    elevation: 10,
  },
  taskSuggestionOutput: {
    width: 160,
    marginVertical: 15,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    backgroundColor: "#f2f2f2",
    padding: 10,
  },
  taskSuggestionButtonRow: {
    width: "100%",
    height: 40,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#777",
    borderTopWidth: 0.5,
    borderColor: "#555",
  },
  taskSuggestionRejectButton: {
    width: 100,
    height: "100%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRightWidth: 1,
    borderColor: "#555",
  },
  taskSuggestionAcceptButton: {
    width: 100,
    height: "100%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  minimalPopup: {
    position: "absolute",
    top: 40,
    right: 40,
    width: "auto",
    height: 50,
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#777",
    borderRadius: 20,
    backgroundColor: "#d1d1d1",
    paddingHorizontal: 10,
    zIndex: 3,
    elevation: 10,
  },
  minimalPopupSuccess: {
    backgroundColor: "#448c25",
  },
  settingsPopup: {
    width: 370,
    height: 220,
    justifyContent: "space-between",
    borderWidth: 0.5,
    borderColor: "#777",
    borderRadius: 25,
    backgroundColor: "#e0e0e0",
    padding: 25,
  },
  settingsButton: {
    width: 150,
    height: 50,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#BBB",
    borderRadius: 15,
    backgroundColor: "rgba(0,0,0,0.1)",
    paddingHorizontal: 10,
  },
  pickerPopup: {
    width: 400,
    flexDirection: "column",
    alignItems: "center",
    borderWidth: 0.5,
    borderColor: "#777",
    borderRadius: 25,
    backgroundColor: "#e0e0e0",
    padding: 25,
  },
  pickerOptionsList: {
    width: "100%",
    marginTop: 20,
    borderRadius: 15,
    backgroundColor: "#d1d1d1",
    overflow: "hidden",
  },
  pickerOption: {
    width: "100%",
    height: 50,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderColor: "#ededed",
    paddingHorizontal: 15,
  },
  pickerRoundOptionsRow: {
    width: "100%",
    marginTop: 20,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  pickerRoundOption: {
    width: 80,
    height: 80,
    marginRight: 10,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#d1d1d1",
    padding: 5,
  },
  selectedPickerRoundOption: {
    backgroundColor: "#bfbfbf",
    borderWidth: 1,
    borderColor: "#777",
  },
  expandableSelection: {
    width: "100%",
    marginTop: 20,
    borderRadius: 15,
    backgroundColor: "#f2f2f2",
    padding: 10,
  },
  toggleSwitchContainer: {
    width: 50,
    height: 30,
    borderRadius: 15,
    justifyContent: "center",
    padding: 2,
  },
  toggleSwitchBall: {
    width: 23,
    height: 23,
    borderRadius: 13,
    backgroundColor: "white",
  },
  dateContainer: {
    borderRadius: 20,
    borderColor: "gray",
    backgroundColor: "#eaeaea",
    padding: 20,
  },
  datePicker: {
    backgroundColor: "#eaeaea",
    calendarBackground: "#eaeaea",
    textSectionTitleColor: "#333333",
    selectedDayBackgroundColor: "#0095d6",
    selectedDayTextColor: "#000",
    todayTextColor: "#01597f",
    dayTextColor: "#000",
    textDisabledColor: "#8e8d8d",
    monthTextColor: "#000",
  },
  taskControlScroll: {
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  urgentTask: {
    backgroundColor: "#f7b9b2",
  },
  urgentTaskCategoryLabel: {
    backgroundColor: "#e29b93",
  },
  selectedPickerOption: {
    backgroundColor: "#bfbfbf",
  },
  taskAnalysisButtonGradient: {
    colors: ["#63ffbe", "#29e8d5"],
  },
  switch: {
    backgroundColor: "#cecece",
  },
  chartCaptionLabel: {
    margin: 5,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 15,
    borderColor: "#999",
    backgroundColor: "#DDD",
    paddingVertical: 7,
    paddingHorizontal: 10,
  },
  icon: {
    color: "black",
  },
  statusBar: {
    style: "dark",
    backgroundColor: "#eaeaea",
  },
  navigationBar: {
    color: "#eaeaea",
    buttonStyle: "dark",
  },
});

export default lightStyles;
