import { StyleSheet } from "react-native";
import { Dimensions } from "react-native";

const screenWidth = Dimensions.get("window").width;
const screenHeight = Dimensions.get("window").height;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    minWidth: screenWidth,
    minHeight: screenHeight,
    backgroundColor: "#000",
  },
  fullscreenArea: {
    position: "absolute",
    minWidth: screenWidth,
    minHeight: screenHeight,
    flexDirection: "row",
    zIndex: 1,
  },
  menuLeft: {
    width: "60%",
    height: "100%",
    backgroundColor: "#000",
    borderRightWidth: 1,
    borderRightColor: "#555",
    padding: 30,
  },
  menuRight: {
    minWidth: "40%",
    minHeight: "100%",
  },
  topBar: {
    width: screenWidth,
    height: 60,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    backgroundColor: "#000",
    paddingLeft: 17,
  },
  tasksArea: {
    width: screenWidth - 50,
    height: screenHeight - 110,
    marginTop: 10,
    alignSelf: "center",
    flexDirection: "column",
    justifyContent: "space-between",
    borderRadius: 20,
    backgroundColor: "#191919",
    padding: 20,
  },
  text: {
    fontFamily: "ReadexPro-Regular",
    color: "#fff",
  },
  header: {
    fontFamily: "ReadexPro-Bold",
    color: "#fff",
  },
  category: {
    fontFamily: "ReadexPro-Regular",
    fontSize: 12,
    color: "#fff",
  },
  task: {
    minWidth: screenWidth - 90,
    height: 100,
    justifyContent: "center",
    backgroundColor: "#111",
    padding: 10,
  },
  deleteButton: {
    width: 70,
    height: 100,
    justifyContent: "center",
    alignItems: "center",
    margin: 0,
    backgroundColor: "#dd2727",
  },
  completedButton: {
    width: 70,
    height: 100,
    justifyContent: "center",
    alignItems: "center",
    margin: 0,
    backgroundColor: "#3ba0d3",
  },
  magicAIButton: {
    width: 60,
    height: 60,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 30,
    overflow: "hidden",
  },
  addTaskButton: {
    width: 155,
    height: 60,
    marginLeft: 17,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 30,
    backgroundColor: "#0f776d",
    paddingLeft: 7,
  },
  taskPopup: {
    width: 400,
    height: 560,
    alignItems: "center",
    borderRadius: 25,
    backgroundColor: "#222",
    padding: 25,
  },
  taskInput: {
    width: "100%",
    height: 410,
    marginVertical: 20,
    backgroundColor: "#191919",
    borderRadius: 15,
    padding: 10,
    color: "#fff",
  },
  popupButtonRow: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  commonButton: {
    width: 100,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 10,
    borderColor: "#4c4c4c",
    backgroundColor: "#1e1e1e",
  },
  messagePopup: {
    width: 400,
    height: 200,
    justifyContent: "space-between",
    alignItems: "flex-start",
    borderRadius: 25,
    backgroundColor: "#222",
    padding: 25,
  },
  minimalPopup: {
    position: "absolute",
    top: 70,
    right: 40,
    width: "auto",
    height: 50,
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#777",
    borderRadius: 20,
    backgroundColor: "#333",
    paddingHorizontal: 10,
    zIndex: 1,
  },
});

export default styles;
